TAP version 13
    # Subtest: exceed_plan
    1..1
    ok 1 - (unnamed test)
ok 1 - exceed_plan ___/# time=[0-9.]+(ms)?/~~~

not ok 2 - Error: test count exceeds plan
  ---
  {"at":{"column":7,"file":"test/test/catch-tap-throws.js","function":"exceed_plan","line":9},"count":2,"message":"Error: test count exceeds plan","plan":1,"source":"t.pass()\n","test":"exceed_plan"}
  ...
    # Subtest: multiple_end
    ok 1 - (unnamed test)
    1..1
ok 3 - multiple_end ___/# time=[0-9.]+(ms)?/~~~

not ok 4 - Error: test end() method called more than once
  ---
  {"message":"Error: test end() method called more than once","test":"multiple_end"}
  ...
    # Subtest: assert_after_end
    ok 1 - (unnamed test)
    1..1
ok 5 - assert_after_end ___/# time=[0-9.]+(ms)?/~~~

not ok 6 - Error: test after end() was called
  ---
  {"at":{"column":7,"file":"test/test/catch-tap-throws.js","function":"assert_after_end","line":29},"count":2,"message":"Error: test after end() was called","plan":1,"source":"t.pass()\n","test":"assert_after_end"}
  ...
1..6
# failed 3 of 6 tests
___/# time=[0-9.]+(ms)?/~~~

